
# Choose the dialect among ['pgx', 'mysql', 'sqlite3']
DB_DRIVER = "sqlite3"

# mysql =>  user:password@tcp(host:port)/db?k=v
# pgx   =>  user:password@host:port/db?k=v
DB_DSN = "D:\\GOLANG_CODE\\go_flutter_count\\db.sqlite"

# target database name you choose , not needed for sqlite and pgx, only for mysql
DB_NAME = ""

# target tables used for stmt generation
TABLES = ["COUNT", "COUNT_RECORD"]

# Enable logger or not
LOG_ENABLED = true
	