// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package dao

import (
	"database/sql"
	"time"
)

type COUNT struct {
	Key       string    `db:"key" json:"key"`
	Value     int64     `db:"value" json:"value"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type COUNTRECORD struct {
	ID        int64         `db:"id" json:"id"`
	Key       string        `db:"key" json:"key"`
	OldValue  sql.NullInt64 `db:"old_value" json:"old_value"`
	NewValue  sql.NullInt64 `db:"new_value" json:"new_value"`
	CreatedAt time.Time     `db:"created_at" json:"created_at"`
}
