// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package dao

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountCounterRecords(ctx context.Context) (int64, error)
	CreateCounterRecord(ctx context.Context, newValue sql.NullInt64) (sql.Result, error)
	DecrementCountValue(ctx context.Context) error
	GetCountValue(ctx context.Context) (int64, error)
	GetCounterRecords(ctx context.Context) ([]COUNTRECORD, error)
	IncrementCountValue(ctx context.Context) error
	InitCountValue(ctx context.Context) (sql.Result, error)
	ResetCountValue(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
